[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F429ZI --catch-hardfault --always-print-stacktrace'

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[env]
DEFMT_LOG = "debug"
